In [1]:
import sys
sys.path.append('../')
from ISI import Problem, Solution, excel_to_pb, Meta_param
import numpy as np
import caffeine
%load_ext jupyternotify

<IPython.core.display.Javascript object>

In [2]:
%load_ext autoreload
%autoreload 2

## Data

In [3]:
path = '../Data/Burundi final v2.xlsx'

# Initial values of tuning parameters

In [4]:
#Leo to do

nbr_tours_init = 2
t_virt_init = 1
H_init = 2   #time splitting
time_step_init = 0.5    #time fusing
cooling_fac_init = 0.9
rho_percent_init = 0.3

In [5]:
nbr_tours = nbr_tours_init
t_virt = t_virt_init
H = H_init 
time_step = time_step_init
cooling_fac = cooling_fac_init
rho_percent = rho_percent_init

## Fixed parameters

In [6]:
T = 2 #not sure yet
Q2 = 20
v = 40
t_load = 0.5
c_per_km = 0.1
Tmax = 10
print(2)

2


In [7]:
def print_stats(test_result):
    print('Test statistics for the parameter of {}'.format(test_result['parameter']))
    for i in range(len(test_result['stats'][0]['clusters'])):
        print('Cluster {}:'.format(test_result['stats'][0]['clusters'][i]))
        print('Value', '\t', 'Solution Cost','\t'*2, 'Running Time')
        for j in range(len(test_result['stats'])):
            print(test_result['stats'][j]['value'],'\t', test_result['stats'][j]['costs'][i], '\t',test_result['stats'][j]['running_times'][i])         

## Number of tours of a vehicle per time step

In [87]:
nbr_tours_val = [i for i in range(max(1, nbr_tours_init-2), nbr_tours_init+3)]   # initial value +-2
name_parameter = 'number of tours of a vehicle per time step'

stats = []
test_result = {'parameter': name_parameter, 'stats': stats}
for val in nbr_tours_val:
    nbr_tours = val
    dictionary = {'value': val}
    print('Computing solution for {} = {}'.format(test_result['parameter'], dictionary['value']))
    schools, warehouses, Q1, V_number, makes = excel_to_pb(path, nbr_tours = nbr_tours)
    problem = Problem(warehouses, schools, Q1, T=T, Q2 = Q2, v=v, t_load=t_load, c_per_km=c_per_km, Tmax=Tmax,V_number = V_number, makes = makes, t_virt = t_virt, H=H)
    meta_params = Meta_param()
    meta_params.rho_percent = rho_percent
    meta_params.cooling = cooling_fac
    solutions = problem.final_solver(meta_params, time_step=time_step , plot_cluster = False, info = False, comp_small_cl = True, return_var = True)
    running_times, costs, names = [],[],[]
    for i in range(len(solutions)):
        running_times.append(solutions[i].running_time['Define problem'] + solutions[i].running_time['Solve problem '] + solutions[i].running_time['Compute TSPs'])
        costs.append(solutions[i].solution_best.cost)
        names.append(solutions[i].solution.problem.Warehouses[-1]['name'])
    dictionary['running_times'], dictionary['costs'], dictionary['clusters'] = running_times, costs, names
    stats.append(dictionary)
print_stats(test_result)
nbr_tours = nbr_tours_init
%notify -m "Cell is complete!"

Computing solution for number of tours of a vehicle per time step = 1
Found 3 clusters!
Skipping cluster 1 of 3 of size 107! (Belonging to WH BUJUMBURA)
Starting to compute cluster 2 of 3! (Belonging to WH NGOZI)
 Total algorithm time = 181.07 
Total ISI running times : 
  Define problem  :  95.8
  Solve problem   :  76.56
  Compute TSPs  :  2.05
  Visualisation  :  0.08
  
Cluster 2 of 3 computed!
Starting to compute cluster 3 of 3! (Belonging to WH GITEGA)
 Total algorithm time = 252.11 
Total ISI running times : 
  Define problem  :  138.46
  Solve problem   :  101.84
  Compute TSPs  :  2.56
  Visualisation  :  0.13
  
Cluster 3 of 3 computed!
Computing solution for number of tours of a vehicle per time step = 2
Found 3 clusters!
Skipping cluster 1 of 3 of size 107! (Belonging to WH BUJUMBURA)
Starting to compute cluster 2 of 3! (Belonging to WH NGOZI)
 Total algorithm time = 560.58 
Total ISI running times : 
  Define problem  :  345.46
  Solve problem   :  190.28
  Compute TSPs  :

 Total algorithm time = 1522.08 
Total ISI running times : 
  Define problem  :  1114.93
  Solve problem   :  342.4
  Compute TSPs  :  2.07
  Visualisation  :  0.19
  
Cluster 3 of 3 computed!
Test statistics for the parameter of number of tours of a vehicle per time step
Cluster NGOZI:
Value 	 Solution Cost 		 Running Time
1 	 0.1989303816194183 	 174.4058394432068
2 	 0.2142796686099153 	 537.7462661266327
3 	 0.22137372138321873 	 1071.0886180400848
4 	 0.1989303816194183 	 1766.7397933006287
Cluster GITEGA:
Value 	 Solution Cost 		 Running Time
1 	 0.1870245126547535 	 242.85744762420654
2 	 0.23300060172848414 	 490.3735032081604
3 	 0.2508947243597498 	 1132.063154220581
4 	 0.19639235863599167 	 1459.4025399684906


<IPython.core.display.Javascript object>

## Time splitting (time slice in weeks over which the algorithm runs the ISI)

In [88]:
T_H_t_virt_val = [(2,1,1), (3,3,0),(3,1.5,1),(3,1.5,2)]            # initial value +-2
name_parameter = 'Time horizon, H, # of virtual time steps'

stats = []
test_result = {'parameter': name_parameter, 'stats': stats}
for (T_val, H_val, virt_val) in T_H_t_virt_val:
    T=T_val
    H = H_val
    t_virt = virt_val
    dictionary = {'value': (T_val, H_val, virt_val)}
    print('Computing solution for {} = {}'.format(test_result['parameter'], dictionary['value']))
    schools, warehouses, Q1, V_number, makes = excel_to_pb(path, nbr_tours = nbr_tours)
    problem = Problem(warehouses, schools, Q1, T=T, Q2 = Q2, v=v, t_load=t_load, c_per_km=c_per_km, Tmax=Tmax,V_number = V_number, makes = makes, t_virt = t_virt, H=H)
    meta_params = Meta_param()
    meta_params.rho_percent = rho_percent
    meta_params.cooling = cooling_fac
    solutions = problem.final_solver(meta_params, time_step=time_step , plot_cluster = False, info = False, comp_small_cl = True, return_var = True)
    running_times, costs, names = [],[],[]
    for i in range(len(solutions)):
        running_times.append(solutions[i].running_time['Define problem'] + solutions[i].running_time['Solve problem '] + solutions[i].running_time['Compute TSPs'])
        costs.append(solutions[i].solution_best.cost)
        names.append(solutions[i].solution.problem.Warehouses[-1]['name'])
    dictionary['running_times'], dictionary['costs'], dictionary['clusters'] = running_times, costs, names
    stats.append(dictionary)
print_stats(test_result)
T=2
H = H_init
t_virt = t_virt_init

Computing solution for Time horizon, H, # of virtual time steps = (2, 1, 1)
Found 3 clusters!
Skipping cluster 1 of 3 of size 107! (Belonging to WH BUJUMBURA)
Starting to compute cluster 2 of 3! (Belonging to WH NGOZI)
 Total algorithm time = 551.09 
Total ISI running times : 
  Define problem  :  344.48
  Solve problem   :  179.73
  Compute TSPs  :  4.15
  Visualisation  :  0.21
  
Cluster 2 of 3 computed!
Starting to compute cluster 3 of 3! (Belonging to WH GITEGA)
candidates:  [[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0 11  0  0 10  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  5  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  

candidates:  [[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0 14  0  0  9  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0 19  0  0 19  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]]
1. t,n,k,route,solution.Y[t,n,k,:]:  4 1 2 [21, 33, 42, 13, 19, 37, 38, 29, 27, 32, 50, 16, 49, 34, 41, 17, 39, 44, 51] [False False False False False False False False False False False  True
 False False  True  True False  True False  True False False False False
 False  True False  True False False  True  True  True False False  Tru

candidates:  [[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0 19  0  0  4  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0 19  0  0 19  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]]
1. t,n,k,route,solution.Y[t,n,k,:]:  4 1 2 [21, 33, 42, 13, 19, 37, 38, 29, 27, 32, 50, 16, 49, 34, 41, 17, 39, 44, 51] [False False False False False False False False False False False  True
 False False  True  True False  True False  True False False False False
 False  True False  True False False  True  True  True False False  Tru

candidates:  [[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0 19  0  0  4  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0 19  0  0 19  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]]
1. t,n,k,route,solution.Y[t,n,k,:]:  4 1 5 [7, 2, 15, 37, 4, 22, 25, 48, 6, 8, 23, 47, 36, 43, 45, 46, 12, 11, 3] [ True  True  True False  True  True  True False False  True  True False
 False  True False False False False False False  True  True False  True
 False False False False False False False False False False  True  True
 Fal

 Total algorithm time = 440.33 
Total ISI running times : 
  Define problem  :  278.0
  Solve problem   :  141.97
  Compute TSPs  :  3.12
  Visualisation  :  0.19
  
Cluster 3 of 3 computed!
Computing solution for Time horizon, H, # of virtual time steps = (3, 3, 0)
Found 3 clusters!
Skipping cluster 1 of 3 of size 107! (Belonging to WH BUJUMBURA)
Starting to compute cluster 2 of 3! (Belonging to WH NGOZI)
candidates:  [[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 1  1  3  0  1  1  1  1  1  1  0  1  1  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0 14  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [12  0  0  0  0  0  0  7  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0 12  3  0  0  0  0  5  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 

 Total algorithm time = 1561.67 
Total ISI running times : 
  Define problem  :  797.17
  Solve problem   :  711.17
  Compute TSPs  :  2.9
  Visualisation  :  0.17
  
Cluster 2 of 3 computed!
Starting to compute cluster 3 of 3! (Belonging to WH GITEGA)
candidates:  [[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 1  1  1  1  0  1  0  1  0  1  1  1  1  4  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0 13  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0 10  0  0  0  0 19  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 4  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0 12  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0 14  0  0

 Total algorithm time = 1876.59 
Total ISI running times : 
  Define problem  :  910.68
  Solve problem   :  910.19
  Compute TSPs  :  3.9
  Visualisation  :  0.22
  
Cluster 3 of 3 computed!
Computing solution for Time horizon, H, # of virtual time steps = (3, 1.5, 1)
Found 3 clusters!
Skipping cluster 1 of 3 of size 107! (Belonging to WH BUJUMBURA)
Starting to compute cluster 2 of 3! (Belonging to WH NGOZI)
 Total algorithm time = 1363.95 
Total ISI running times : 
  Define problem  :  777.93
  Solve problem   :  529.25
  Compute TSPs  :  6.37
  Visualisation  :  0.32
  
Cluster 2 of 3 computed!
Starting to compute cluster 3 of 3! (Belonging to WH GITEGA)
 Total algorithm time = 806.86 
Total ISI running times : 
  Define problem  :  522.08
  Solve problem   :  249.59
  Compute TSPs  :  4.4
  Visualisation  :  0.24
  
Cluster 3 of 3 computed!
Computing solution for Time horizon, H, # of virtual time steps = (3, 1.5, 2)
Found 3 clusters!
Skipping cluster 1 of 3 of size 107! (Belongin

candidates:  [[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  1  1  0  0  0  1  0  1  1  0  0  1  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 7  0  0  0  0  0  0 19  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [18  0  7  0  0  6  0 11  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 6  0  0  0  0  0  2  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]]
1. t,n,k,route,solution.Y[t,n,k,:]:  0 1 2 [4] [False False  True False False

candidates:  [[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 1  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0 19  0  0  0  0  0  0  0  0  2  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [10  0 16  0  0  5  0 13  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 6  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]]
1. t,n,k,route,solution.Y[t,n,k,:]:  4 1 0 [38, 37, 14, 47, 40, 7, 42, 23, 16

candidates:  [[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0 19  0  0  0  0  0  0  0  0  2  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [12  0 16  0  0  2  0 15  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 6  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]]
1. t,n,k,route,solution.Y[t,n,k,:]:  5 1 0 [24, 49, 11, 35, 6, 29] [False Fal

candidates:  [[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 1  0  0  0  0  0  0 19  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [14  0 17  0  0  5  0 15  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]]
1. t,n,k,route,solution.Y[t,n,k,:]:  4 1 2 [24, 9, 48, 13, 43, 41, 19, 15, 36

candidates:  [[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0 19  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [14  0 16  0  0  7  0 13  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]]
1. t,n,k,route,solution.Y[t,n,k,:]:  2 1 7 [8, 27, 18, 45, 17, 50, 47, 14, 29

 Total algorithm time = 1367.36 
Total ISI running times : 
  Define problem  :  713.17
  Solve problem   :  602.25
  Compute TSPs  :  5.86
  Visualisation  :  0.3
  
Cluster 2 of 3 computed!
Starting to compute cluster 3 of 3! (Belonging to WH GITEGA)
candidates:  [[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 1  1  1  1  1  1  2  1  1  1  1  1  1  1  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  4  0  4  0  9  0  6  0  0  0  6  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0 16  0  0 10  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 8  0  0  7  0  0

candidates:  [[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  1  0  1  1  0  1  1  1  1  1  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  4  0  4  0  9  0  0  0  0  0 12  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0 16  0  0 10  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 8  0  0  7  0  0  0  0  9  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]]
1. t,n,k,route,solution.Y[t,n,k,:]:  2 1 1 [51, 17, 39, 44] [False False Fals

candidates:  [[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  1  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  1  0  9  0  7  0  0  0  0  0 12  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0 16  0  0 10  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 8  0  0  7  0  0  0  0  9  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]]
1. t,n,k,route,solution.Y[t,n,k,:]:  0 1 1 [3] [False  True False False False

candidates:  [[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0 12  0  4  0  0  0  0  0 12  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0 16  0  0 10  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 7  0  0  8  0  0  0  0  9  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]]
1. t,n,k,route,solution.Y[t,n,k,:]:  2 1 3 [21, 33, 42, 41, 34, 49, 37, 38, 1

candidates:  [[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0 14  0  2  0  0  0  0  0 12  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0 18  0  0 10  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 7  0  0  6  0  0  0  0  9  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]]
1. t,n,k,route,solution.Y[t,n,k,:]:  4 1 5 [11, 10, 8, 23, 6, 5, 25, 22, 18, 

candidates:  [[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0 15  0  0  0  0  0  0  0 12  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0 19  0  0  8  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 3  0  0  6  0  0  0  0 14  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]]
1. t,n,k,route,solution.Y[t,n,k,:]:  5 1 0 [21, 51, 44] [False False False Fa

candidates:  [[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0 15  0  0  0  0  0  0  0 12  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0 19  0  0 17  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0 14  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]]
1. t,n,k,route,solution.Y[t,n,k,:]:  2 1 3 [21, 33, 30, 15, 19, 38, 37, 49, 3

candidates:  [[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0 18  0  0  0  0  0  0  0 16  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0 19  0  0 16  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0 13  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]]
1. t,n,k,route,solution.Y[t,n,k,:]:  2 1 3 [44, 33, 41, 37, 38, 48, 6, 23, 8,

candidates:  [[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0 11  0  0  0  0  0  0  0 18  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0 19  0  0 17  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0 14  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]]
1. t,n,k,route,solution.Y[t,n,k,:]:  2 1 11 [21, 42, 13, 19, 11, 46, 45, 43, 

candidates:  [[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0 13  0  0  0  0  0  0  0 18  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0 19  0  0 17  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0 14  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]]
1. t,n,k,route,solution.Y[t,n,k,:]:  5 1 8 [3, 46, 45, 10, 6, 5, 23, 8, 31, 4

candidates:  [[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0 11  0  0  0  0  0  0  0 17  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0 19  0  0 17  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0 14  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]]
1. t,n,k,route,solution.Y[t,n,k,:]:  4 1 5 [14, 11, 12, 48, 25, 4, 18, 22, 28

 Total algorithm time = 1108.59 
Total ISI running times : 
  Define problem  :  677.27
  Solve problem   :  385.66
  Compute TSPs  :  5.87
  Visualisation  :  0.31
  
Cluster 3 of 3 computed!
Test statistics for the parameter of Time horizon, H, # of virtual time steps
Cluster NGOZI:
Value 	 Solution Cost 		 Running Time
(2, 1, 1) 	 0.3417060202751969 	 528.3570792675018
(3, 3, 0) 	 0.27908017681974745 	 1511.2452428340912
(3, 1.5, 1) 	 0.47242364344419585 	 1313.5488328933716
(3, 1.5, 2) 	 0.35937780694881055 	 1321.2893161773682
Cluster GITEGA:
Value 	 Solution Cost 		 Running Time
(2, 1, 1) 	 0.32694463467527607 	 423.09533762931824
(3, 3, 0) 	 0.42887989810086735 	 1824.7687311172485
(3, 1.5, 1) 	 0.5858720022807328 	 776.0815393924713
(3, 1.5, 2) 	 0.41227719170144184 	 1068.8025624752045


## Time fusing (time slice in weeks that gets fused to one time step)

In [ ]:
time_step_val = [i for i in np.arange(max(0.5, time_step_init-1.5), time_step_init+2, 0.5)]            # initial value +-1.5
name_parameter = 'Time fusing (time slice in weeks)'

stats = []
test_result = {'parameter': name_parameter, 'stats': stats}
for val in time_step_val:
    time_step = val
    dictionary = {'value': val}
    print('Computing solution for {} = {}'.format(test_result['parameter'], dictionary['value']))
    schools, warehouses, Q1, V_number, makes = excel_to_pb(path, nbr_tours = nbr_tours)
    problem = Problem(warehouses, schools, Q1, T=T, Q2 = Q2, v=v, t_load=t_load, c_per_km=c_per_km, Tmax=Tmax,V_number = V_number, makes = makes, t_virt = t_virt, H=H)
    meta_params = Meta_param()
    meta_params.rho_percent = rho_percent
    meta_params.cooling = cooling_fac
    solutions = problem.final_solver(meta_params, time_step=time_step , plot_cluster = False, info = False, comp_small_cl = True, return_var = True)
    running_times, costs, names = [],[],[]
    for i in range(len(solutions)):
        running_times.append(solutions[i].running_time['Define problem'] + solutions[i].running_time['Solve problem '] + solutions[i].running_time['Compute TSPs'])
        costs.append(solutions[i].solution_best.cost)
        names.append(solutions[i].solution.problem.Warehouses[-1]['name'])
    dictionary['running_times'], dictionary['costs'], dictionary['clusters'] = running_times, costs, names
    stats.append(dictionary)
print_stats(test_result)
time_step = time_step_init

## Cooling factor

In [ ]:
cooling_fac_val = [i for i in np.arange(max(0.01, cooling_fac_init-0.15), cooling_fac_init+0.2, 0.05)]            # initial value +- 0.15
name_parameter = 'Cooling factor'

stats = []
test_result = {'parameter': name_parameter, 'stats': stats}
for val in cooling_fac_val:
    cooling_fac = val
    dictionary = {'value': val}
    print('Computing solution for {} = {}'.format(test_result['parameter'], dictionary['value']))
    schools, warehouses, Q1, V_number, makes = excel_to_pb(path, nbr_tours = nbr_tours)
    problem = Problem(warehouses, schools, Q1, T=T, Q2 = Q2, v=v, t_load=t_load, c_per_km=c_per_km, Tmax=Tmax,V_number = V_number, makes = makes, t_virt = t_virt, H=H)
    meta_params = Meta_param()
    meta_params.rho_percent = rho_percent
    meta_params.cooling = cooling_fac
    solutions = problem.final_solver(meta_params, time_step=time_step , plot_cluster = False, info = False, comp_small_cl = True, return_var = True)
    running_times, costs, names = [],[],[]
    for i in range(len(solutions)):
        running_times.append(solutions[i].running_time['Define problem'] + solutions[i].running_time['Solve problem '] + solutions[i].running_time['Compute TSPs'])
        costs.append(solutions[i].solution_best.cost)
        names.append(solutions[i].solution.problem.Warehouses[-1]['name'])
    dictionary['running_times'], dictionary['costs'], dictionary['clusters'] = running_times, costs, names
    stats.append(dictionary)
print_stats(test_result)
cooling_fac = cooling_fac_init

Computing solution for Cooling factor = 0.75
Found 3 clusters!
Skipping cluster 1 of 3 of size 107! (Belonging to WH BUJUMBURA)
Starting to compute cluster 2 of 3! (Belonging to WH NGOZI)
 Total algorithm time = 200.31 
Total ISI running times : 
  Define problem  :  128.36
  Solve problem   :  63.01
  Compute TSPs  :  0.68
  Visualisation  :  0.04
  
Cluster 2 of 3 computed!
Starting to compute cluster 3 of 3! (Belonging to WH GITEGA)
 Total algorithm time = 313.78 
Total ISI running times : 
  Define problem  :  205.11
  Solve problem   :  95.62
  Compute TSPs  :  1.13
  Visualisation  :  0.08
  
Cluster 3 of 3 computed!
Computing solution for Cooling factor = 0.8
Found 3 clusters!
Skipping cluster 1 of 3 of size 107! (Belonging to WH BUJUMBURA)
Starting to compute cluster 2 of 3! (Belonging to WH NGOZI)
 Total algorithm time = 342.48 
Total ISI running times : 
  Define problem  :  211.8
  Solve problem   :  115.52
  Compute TSPs  :  1.22
  Visualisation  :  0.08
  
Cluster 2 of 3 c

candidates:  [[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  1  0  0  0  1  0  1  1  1  1  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0 19  0 11  0  3  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  5  0  0  0  0  0  0  0  0  0  0  0  0]]]
1. t,n,k,route,solution.Y[t,n,k,:]:  2 1 5 [51, 17, 44] [False False False False False False False False False False False False
 False False False  True False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False  True False False False F

candidates:  [[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0 19  0 19  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]]
1. t,n,k,route,solution.Y[t,n,k,:]:  2 1 1 [44, 51, 42, 39, 17, 34, 41, 16, 50, 32, 6, 23, 8, 47, 36, 43, 45, 46, 3] [False  True False False  True False  True False False False False False
 False False  True  True False False False False False  True False False
 False False False False False False  True False  True False  True False
 

candidates:  [[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0 19  0 19  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]]
1. t,n,k,route,solution.Y[t,n,k,:]:  2 1 3 [21, 33, 42, 13, 49, 27, 29, 22, 25, 48, 12, 4, 37, 38, 19, 15, 30, 2, 7] [ True False  True False False  True False False False False  True  True
 False  True False False False  True False  True  True False False  True
 False  True False  True  True False False  True False False False  True
 

candidates:  [[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0 19  0 19  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]]
1. t,n,k,route,solution.Y[t,n,k,:]:  2 1 3 [21, 33, 42, 13, 49, 27, 29, 22, 25, 48, 12, 4, 37, 38, 19, 15, 30, 2, 7] [ True False  True False False  True False False False False  True  True
 False  True False False False  True False  True  True False False  True
 False  True False  True  True False False  True False False False  True
 

candidates:  [[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0 19  0 19  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]]
1. t,n,k,route,solution.Y[t,n,k,:]:  2 1 3 [21, 33, 42, 51, 44, 39, 17, 34, 49, 16, 27, 29, 38, 37, 19, 13, 30, 2, 7] [ True False False False False  True False False False False False  True
 False False  True  True False  True False  True False False False False
 False  True False  True  True False False  True  True False False  True


candidates:  [[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0 19  0 19  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]]
1. t,n,k,route,solution.Y[t,n,k,:]:  2 1 3 [21, 33, 42, 51, 44, 39, 17, 41, 34, 49, 16, 50, 29, 37, 38, 19, 13, 30, 2] [ True False False False False False False False False False False  True
 False False  True  True False  True False  True False False False False
 False False False  True  True False False  True  True False False  True

candidates:  [[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 1  1  1  1  1  0  2  1  1  1  1  1  1  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0 19  0 19  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]]
1. t,n,k,route,solution.Y[t,n,k,:]:  0 1 6 [8, 23] [False False False False False False  True False False False False False
 False False False False False False False False False  True False False
 False False False False False False False False False False False False
 False False False False False False False False False False False 

candidates:  [[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0 19  0 19  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]]
1. t,n,k,route,solution.Y[t,n,k,:]:  2 1 1 [15, 27, 50, 32, 22, 4, 25, 48, 6, 23, 8, 47, 36, 43, 45, 46, 12, 11, 3] [False  True  True False  True False  True False False  True  True False
 False  True False False False False False False  True  True False  True
 False  True False False False False  True False False False  True False
 F

 Total algorithm time = 603.02 
Total ISI running times : 
  Define problem  :  392.06
  Solve problem   :  185.07
  Compute TSPs  :  2.42
  Visualisation  :  0.15
  
Cluster 3 of 3 computed!
Computing solution for Cooling factor = 0.9500000000000002
Found 3 clusters!
Skipping cluster 1 of 3 of size 107! (Belonging to WH BUJUMBURA)
Starting to compute cluster 2 of 3! (Belonging to WH NGOZI)
candidates:  [[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
  [1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0]]

 [[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
  [2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0]]

 [[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
  [8 0 0 0 0 1 0 9 0 0 0 0 0 0 0 0 0 2 0 0]]

 [[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
  [2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 7 0 0]]

 [[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
  [0 7 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]]
1. t,n,k,route,solution.Y[t,n,k,:]:  0 1 0 [38] [False False False False False False False False False False False False
 False False False Fal

candidates:  [[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [19  0  0  0  0  0  0 19  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]]
1. t,n,k,route,solution.Y[t,n,k,:]:  2 1 7 [8, 16, 23, 14, 49, 11, 24, 9, 48, 13, 19, 15, 36, 26, 39, 32, 31, 30, 51] [False False False False False False  True  True False  True False  True
  True  True  True False False  True False False False  True  True False
  True False False False  True  True  True False False False  True False


## Rho (in percent of numbers of schools)

In [ ]:
rho_percent_val = [i for i in np.arange(max(0.05, rho_percent_init-0.2), rho_percent_init+0.3, 0.1)]            # initial value +- 0.2
name_parameter = 'Rho (in percent of numbers of schools)'

stats = []
test_result = {'parameter': name_parameter, 'stats': stats}
for val in rho_percent_val:
    rho_percent = val
    dictionary = {'value': val}
    print('Computing solution for {} = {}'.format(test_result['parameter'], dictionary['value']))
    schools, warehouses, Q1, V_number, makes = excel_to_pb(path, nbr_tours = nbr_tours)
    problem = Problem(warehouses, schools, Q1, T=T, Q2 = Q2, v=v, t_load=t_load, c_per_km=c_per_km, Tmax=Tmax,V_number = V_number, makes = makes, t_virt = t_virt, H=H)
    meta_params = Meta_param()
    meta_params.rho_percent = rho_percent
    meta_params.cooling = cooling_fac
    solutions = problem.final_solver(meta_params, time_step=time_step , plot_cluster = False, info = False, comp_small_cl = True, return_var = True)
    running_times, costs, names = [],[],[]
    for i in range(len(solutions)):
        running_times.append(solutions[i].running_time['Define problem'] + solutions[i].running_time['Solve problem '] + solutions[i].running_time['Compute TSPs'])
        costs.append(solutions[i].solution_best.cost)
        names.append(solutions[i].solution.problem.Warehouses[-1]['name'])
    dictionary['running_times'], dictionary['costs'], dictionary['clusters'] = running_times, costs, names
    stats.append(dictionary)
print_stats(test_result)
rho_percent = rho_percent_init

Computing solution for Rho (in percent of numbers of schools) = 0.09999999999999998
Found 3 clusters!
Skipping cluster 1 of 3 of size 107! (Belonging to WH BUJUMBURA)
Starting to compute cluster 2 of 3! (Belonging to WH NGOZI)
 Total algorithm time = 646.14 
Total ISI running times : 
  Define problem  :  403.71
  Solve problem   :  215.41
  Compute TSPs  :  2.36
  Visualisation  :  0.14
  
Cluster 2 of 3 computed!
Starting to compute cluster 3 of 3! (Belonging to WH GITEGA)
 Total algorithm time = 468.0 
Total ISI running times : 
  Define problem  :  315.3
  Solve problem   :  132.83
  Compute TSPs  :  1.88
  Visualisation  :  0.12
  
Cluster 3 of 3 computed!
Computing solution for Rho (in percent of numbers of schools) = 0.19999999999999998
Found 3 clusters!
Skipping cluster 1 of 3 of size 107! (Belonging to WH BUJUMBURA)
Starting to compute cluster 2 of 3! (Belonging to WH NGOZI)
 Total algorithm time = 750.23 
Total ISI running times : 
  Define problem  :  387.24
  Solve problem 